global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus-0:9500']
    scrape_interval: 15s

  - job_name: 'risingwave-standalone'
    static_configs:
      - targets: ['risingwave-standalone:1250']
    scrape_interval: 5s

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana-0:3001']
    scrape_interval: 15s

  - job_name: 'redpanda'
    static_configs:
      - targets: ['message_queue:9644']
    scrape_interval: 15s

  - job_name: 'rustfs'
    static_configs:
      - targets: ['rustfs:9000']
    scrape_interval: 15s